package ex1;


/**
* ex1/_AppStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from if_question.idl
* Thursday, December 16, 2021 10:15:51 AM WEST
*/

public class _AppStub extends org.omg.CORBA.portable.ObjectImpl implements ex1.App
{

  public ex1.Question[] getquestions ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getquestions", true);
                $in = _invoke ($out);
                ex1.Question $result[] = ex1.AppPackage.qlistHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getquestions (        );
            } finally {
                _releaseReply ($in);
            }
  } // getquestions

  public boolean verifierrep (int idrep, int idQuest)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("verifierrep", true);
                $out.write_long (idrep);
                $out.write_long (idQuest);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return verifierrep (idrep, idQuest        );
            } finally {
                _releaseReply ($in);
            }
  } // verifierrep

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ex1/App:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _AppStub
