package ex1;


/**
* ex1/App.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from if_question.idl
* Thursday, December 16, 2021 10:15:51 AM WEST
*/

public interface App extends AppOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface App
