package ex1;


/**
* ex1/AppHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from if_question.idl
* Thursday, December 16, 2021 10:15:51 AM WEST
*/

abstract public class AppHelper
{
  private static String  _id = "IDL:ex1/App:1.0";

  public static void insert (org.omg.CORBA.Any a, ex1.App that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ex1.App extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ex1.AppHelper.id (), "App");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ex1.App read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AppStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ex1.App value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ex1.App narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ex1.App)
      return (ex1.App)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ex1._AppStub stub = new ex1._AppStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ex1.App unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ex1.App)
      return (ex1.App)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ex1._AppStub stub = new ex1._AppStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
