package ex1;


/**
* ex1/AppOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from if_question.idl
* Thursday, December 16, 2021 10:15:51 AM WEST
*/

public interface AppOperations 
{
  ex1.Question[] getquestions ();
  boolean verifierrep (int idrep, int idQuest);
} // interface AppOperations
