package ex1;


/**
* ex1/AppPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from if_question.idl
* Thursday, December 16, 2021 10:15:51 AM WEST
*/

public abstract class AppPOA extends org.omg.PortableServer.Servant
 implements ex1.AppOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getquestions", new java.lang.Integer (0));
    _methods.put ("verifierrep", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ex1/App/getquestions
       {
         ex1.Question $result[] = null;
         $result = this.getquestions ();
         out = $rh.createReply();
         ex1.AppPackage.qlistHelper.write (out, $result);
         break;
       }

       case 1:  // ex1/App/verifierrep
       {
         int idrep = in.read_long ();
         int idQuest = in.read_long ();
         boolean $result = false;
         $result = this.verifierrep (idrep, idQuest);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ex1/App:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public App _this() 
  {
    return AppHelper.narrow(
    super._this_object());
  }

  public App _this(org.omg.CORBA.ORB orb) 
  {
    return AppHelper.narrow(
    super._this_object(orb));
  }


} // class AppPOA
