package ex1;


/**
* ex1/Question.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from if_question.idl
* Thursday, December 16, 2021 10:15:51 AM WEST
*/

public final class Question implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String ennonce = null;
  public ex1.Response responsesList[] = null;

  public Question ()
  {
  } // ctor

  public Question (int _id, String _ennonce, ex1.Response[] _responsesList)
  {
    id = _id;
    ennonce = _ennonce;
    responsesList = _responsesList;
  } // ctor

} // class Question
