package ex1;


/**
* ex1/QuestionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from if_question.idl
* Thursday, December 16, 2021 10:15:51 AM WEST
*/

abstract public class QuestionHelper
{
  private static String  _id = "IDL:ex1/Question:1.0";

  public static void insert (org.omg.CORBA.Any a, ex1.Question that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ex1.Question extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "id",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "ennonce",
            _tcOf_members0,
            null);
          _tcOf_members0 = ex1.ResponseHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (ex1.repHelper.id (), "rep", _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (ex1.repsHelper.id (), "reps", _tcOf_members0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "responsesList",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (ex1.QuestionHelper.id (), "Question", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ex1.Question read (org.omg.CORBA.portable.InputStream istream)
  {
    ex1.Question value = new ex1.Question ();
    value.id = istream.read_long ();
    value.ennonce = istream.read_string ();
    value.responsesList = ex1.repsHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ex1.Question value)
  {
    ostream.write_long (value.id);
    ostream.write_string (value.ennonce);
    ex1.repsHelper.write (ostream, value.responsesList);
  }

}
