package ex1;


/**
* ex1/repHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from if_question.idl
* Thursday, December 16, 2021 10:15:51 AM WEST
*/

abstract public class repHelper
{
  private static String  _id = "IDL:ex1/rep:1.0";

  public static void insert (org.omg.CORBA.Any a, ex1.Response that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ex1.Response extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = ex1.ResponseHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (ex1.repHelper.id (), "rep", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ex1.Response read (org.omg.CORBA.portable.InputStream istream)
  {
    ex1.Response value = null;
    value = ex1.ResponseHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ex1.Response value)
  {
    ex1.ResponseHelper.write (ostream, value);
  }

}
