package ex1;


/**
* ex1/Response.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from if_question.idl
* Thursday, December 16, 2021 10:15:51 AM WEST
*/

public final class Response implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String ennonce = null;
  public boolean verite = false;

  public Response ()
  {
  } // ctor

  public Response (int _id, String _ennonce, boolean _verite)
  {
    id = _id;
    ennonce = _ennonce;
    verite = _verite;
  } // ctor

} // class Response
