package ex1;

/**
* ex1/ResponseHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from if_question.idl
* Thursday, December 16, 2021 10:15:51 AM WEST
*/

public final class ResponseHolder implements org.omg.CORBA.portable.Streamable
{
  public ex1.Response value = null;

  public ResponseHolder ()
  {
  }

  public ResponseHolder (ex1.Response initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ex1.ResponseHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ex1.ResponseHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ex1.ResponseHelper.type ();
  }

}
